# Generated by Django 6.0.3 on 2026-05-26 13:32

from django.db import migrations, models


def promote_existing_staff_to_owner(apps, schema_editor):
    """
    Bump every existing is_staff=True user to role=OWNER.

    Without this step the AddField default (AUDITOR — read-only) would
    apply to the existing founder + any other admins, instantly locking
    them out of every mutating endpoint. Anyone who's already trusted
    enough to be staff stays at full power until the operator
    intentionally demotes them via /admin/team.
    """
    User = apps.get_model('accounts', 'User')
    User.objects.filter(is_staff=True).update(role='OWNER')


def downgrade_owners_noop(apps, schema_editor):
    """Reverse migration is a no-op — role is going away anyway."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usermfa_mfabackupcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('OWNER', 'Owner'), ('ORDER_MANAGER', 'Order Manager'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('MARKETING', 'Marketing'), ('AUDITOR', 'Auditor')], default='AUDITOR', max_length=32),
        ),
        migrations.RunPython(
            promote_existing_staff_to_owner,
            reverse_code=downgrade_owners_noop,
        ),
    ]
