# Generated by Django 6.0.3 on 2026-05-26 13:54

import uuid
from django.db import migrations, models


def seed_system_roles(apps, schema_editor):
    """
    Create the 5 preset roles as is_system=True records.

    The permission lists here must stay in sync with the snapshots in
    apps/accounts/rbac.py at the time this migration ran — the dict
    is duplicated here on purpose because data migrations must NOT
    import live application code (it can change later and break the
    migration replay).

    Owner gets a snapshot too, but the runtime `permissions_for_role()`
    overrides Owner to return the live PERMISSIONS set so newly added
    codes auto-grant — no migration needed.
    """
    Role = apps.get_model('accounts', 'Role')

    presets = [
        {
            "code": "OWNER",
            "name": "Owner",
            "description": "Full access. Only Owners can change other admins' roles.",
            "permissions": sorted([
                "products.view", "products.update", "products.delete",
                "orders.view", "orders.update", "orders.ship", "orders.refund", "orders.cancel",
                "customers.view", "customers.update",
                "inventory.view", "inventory.update",
                "suppliers.view", "suppliers.update", "suppliers.delete",
                "purchase_orders.view", "purchase_orders.update",
                "purchase_orders.receive", "purchase_orders.cancel",
                "catalog.view", "catalog.update", "catalog.delete",
                "promotions.view", "promotions.update", "promotions.delete",
                "reviews.view", "reviews.moderate", "reviews.delete",
                "contact.view", "contact.respond",
                "analytics.view",
                "reports.view", "reports.export",
                "finances.view", "finances.export",
                "expenses.view", "expenses.update", "expenses.delete",
                "audit.view",
                "team.view", "team.manage",
                "integrations.view", "integrations.update",
            ]),
        },
        {
            "code": "ORDER_MANAGER",
            "name": "Order Manager",
            "description": "Orders, shipping, refunds, customer support.",
            "permissions": sorted([
                "orders.view", "orders.update", "orders.ship", "orders.refund", "orders.cancel",
                "customers.view", "customers.update",
                "contact.view", "contact.respond",
                "reports.view",
                "audit.view",
            ]),
        },
        {
            "code": "INVENTORY_MANAGER",
            "name": "Inventory Manager",
            "description": "Products, variants, inventory, suppliers, purchase orders.",
            "permissions": sorted([
                "products.view", "products.update", "products.delete",
                "inventory.view", "inventory.update",
                "suppliers.view", "suppliers.update", "suppliers.delete",
                "purchase_orders.view", "purchase_orders.update",
                "purchase_orders.receive", "purchase_orders.cancel",
                "catalog.view", "catalog.update", "catalog.delete",
                "reports.view",
            ]),
        },
        {
            "code": "MARKETING",
            "name": "Marketing",
            "description": "Promotions, reviews moderation, analytics.",
            "permissions": sorted([
                "promotions.view", "promotions.update", "promotions.delete",
                "reviews.view", "reviews.moderate", "reviews.delete",
                "analytics.view",
                "reports.view",
                "contact.view", "contact.respond",
            ]),
        },
        {
            "code": "AUDITOR",
            "name": "Auditor",
            "description": "Read-only on every resource. No edits, no deletes.",
            "permissions": sorted([
                "products.view", "orders.view", "customers.view",
                "inventory.view", "suppliers.view", "purchase_orders.view",
                "catalog.view", "promotions.view", "reviews.view",
                "contact.view", "analytics.view", "reports.view",
                "finances.view", "expenses.view", "audit.view", "team.view",
                "integrations.view",
            ]),
        },
    ]

    for preset in presets:
        Role.objects.update_or_create(
            code=preset["code"],
            defaults={
                "name": preset["name"],
                "description": preset["description"],
                "permissions": preset["permissions"],
                "is_system": True,
            },
        )


def remove_system_roles(apps, schema_editor):
    """Reverse: only delete system rows so any user-created customs survive."""
    Role = apps.get_model('accounts', 'Role')
    Role.objects.filter(is_system=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.JSONField(default=list)),
                ('is_system', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['-is_system', 'name'],
            },
        ),
        migrations.RunPython(seed_system_roles, reverse_code=remove_system_roles),
    ]
