# Generated by Django 6.0.3 on 2026-05-24 06:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_product_fulfillment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('key', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomizationField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('key', models.CharField(help_text='Stable identifier used in cart/order payload.', max_length=80)),
                ('label', models.CharField(max_length=200)),
                ('help_text', models.CharField(blank=True, default='', max_length=500)),
                ('field_type', models.CharField(choices=[('text', 'Short text'), ('long_text', 'Long text'), ('image', 'Image upload'), ('select', 'Single choice'), ('position', 'Placement (single choice with preview)')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('surcharge_pence', models.PositiveIntegerField(default=0, help_text='Per-unit surcharge added if the customer fills this field.')),
                ('config', models.JSONField(blank=True, default=dict)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_hoc_customization_fields', to='products.product')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='customizations.customizationtemplate')),
            ],
            options={
                'ordering': ['sort_order', 'label'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCustomizationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customization_template_links', to='products.product')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='customizations.customizationtemplate')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomizationFieldOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('value', models.CharField(help_text='Stable identifier used in cart payload.', max_length=80)),
                ('label', models.CharField(max_length=200)),
                ('surcharge_pence', models.PositiveIntegerField(default=0, help_text="Per-unit surcharge added on top of the field's surcharge.")),
                ('preview_image_url', models.URLField(blank=True, default='', help_text='Thumbnail showing this placement / option visually.', max_length=500)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='customizations.customizationfield')),
            ],
            options={
                'ordering': ['sort_order', 'label'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('field', 'value'), name='uniq_customfield_option_value')],
            },
        ),
        migrations.AddConstraint(
            model_name='customizationfield',
            constraint=models.UniqueConstraint(condition=models.Q(('template__isnull', False)), fields=('template', 'key'), name='uniq_customfield_template_key'),
        ),
        migrations.AddConstraint(
            model_name='customizationfield',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('product', 'key'), name='uniq_customfield_product_key'),
        ),
        migrations.AddConstraint(
            model_name='customizationfield',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', True), ('template__isnull', False)), models.Q(('product__isnull', False), ('template__isnull', True)), _connector='OR'), name='customfield_template_xor_product'),
        ),
        migrations.AddConstraint(
            model_name='productcustomizationtemplate',
            constraint=models.UniqueConstraint(fields=('product', 'template'), name='uniq_product_template'),
        ),
    ]
