# Generated by Django 6.0.3 on 2026-05-24 07:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_fulfillment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='optiontype',
            name='code',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='optionvalue',
            name='swatch_hex',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='optionvalue',
            name='swatch_image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.CreateModel(
            name='ProductOptionType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('option_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='products.optiontype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_type_links', to='products.product')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('product', 'option_type'), name='uniq_product_option_type')],
            },
        ),
    ]
