# Generated by Django 6.0.3 on 2026-05-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_backfill_product_option_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fit_notes',
            field=models.CharField(blank=True, default='', help_text="Short note shown under the size chart (e.g. 'Runs small — size up for thick-furred dogs').", max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='size_chart',
            field=models.JSONField(blank=True, default=dict, help_text='Optional size table. Shape: {columns: [...], rows: [[...]]}. See model docstring for example.'),
        ),
    ]
