# Generated by Django 6.0.3 on 2026-05-24 08:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot_token', models.CharField(help_text='Telegram bot token from @BotFather. Stored server-side and never returned to the client.', max_length=255)),
                ('bot_username', models.CharField(blank=True, default='', help_text='Cached @username of the bot (from getMe). Used to render the t.me/<username> QR code.', max_length=80)),
                ('bot_name', models.CharField(blank=True, default='', help_text='Cached display name of the bot.', max_length=200)),
                ('chat_targets', models.JSONField(blank=True, default=list)),
                ('enabled_events', models.JSONField(blank=True, default=dict)),
                ('low_stock_threshold', models.PositiveSmallIntegerField(default=5)),
                ('is_enabled', models.BooleanField(default=True, help_text='Master kill-switch. When false, notify() silently no-ops.')),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('last_update_id', models.BigIntegerField(default=0, help_text='Highest update_id seen by getUpdates so we only pick up new chats.')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
