# Generated by Django 6.0.3 on 2026-05-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_meta_description_category_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='measure_guide_image_url',
            field=models.URLField(blank=True, default='', help_text='Optional diagram showing where to measure the pet.', max_length=500),
        ),
        migrations.AddField(
            model_name='category',
            name='measure_guide_text',
            field=models.TextField(blank=True, default='', help_text="Plain text instructions, one tip per line (e.g. 'Neck: measure where the collar sits, snug but not tight')."),
        ),
    ]
