# Generated by Django 6.0.3 on 2026-05-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_discount_amount_order_promotion_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='customization_surcharge',
            field=models.PositiveIntegerField(default=0, help_text='Per-unit surcharge from customizations, already folded into unit_price.'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='customizations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
