# Generated by Django 6.0.3 on 2026-05-24 14:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0005_orderitem_customization_surcharge_and_more'),
        ('procurement', '0002_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateField(db_index=True, help_text='The actual date the money left the business — used for HMRC year filing, not the row creation date.')),
                ('category', models.CharField(choices=[('cogs_dropship', 'Cost of goods (dropship)'), ('cogs_inventory', 'Cost of goods (inventory)'), ('stripe_fee', 'Stripe fee'), ('shipping_paid', 'Outbound shipping paid by us'), ('refund_given', 'Refund given to customer'), ('ads', 'Advertising / marketing'), ('software', 'Software subscriptions'), ('postage', 'Postage / packaging materials'), ('accounting', 'Accounting / legal fees'), ('office', 'Office supplies / utilities'), ('other', 'Other')], db_index=True, max_length=32)),
                ('amount_pence', models.PositiveIntegerField(help_text='Total amount paid in pence (gross — includes any VAT).')),
                ('vat_amount_pence', models.PositiveIntegerField(default=0, help_text='VAT included in `amount_pence`, in pence. Only relevant for VAT-registered businesses claiming input tax. Leave 0 if not VAT-registered.')),
                ('currency', models.CharField(default='GBP', help_text='ISO 4217. Always GBP for now — kept for future expansion.', max_length=3)),
                ('description', models.CharField(help_text="Short human-readable description (e.g. 'Temu order for TPH-000005', 'Google Ads — March', 'Vistaprint packaging').", max_length=500)),
                ('receipt_key', models.CharField(blank=True, default='', help_text='Storage key inside the private bucket. Empty until uploaded.', max_length=500)),
                ('receipt_filename', models.CharField(blank=True, default='', help_text="Original filename the admin uploaded — preserved for the year-end CSV export so the accountant sees 'temu-invoice-mar.pdf' not the uuid key.", max_length=255)),
                ('receipt_content_type', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('auto_created', models.BooleanField(db_index=True, default=False, help_text='True for system-generated rows (Stripe fees, COGS). Manual rows added via the admin Finances form are False.')),
                ('external_ref', models.CharField(blank=True, db_index=True, default='', help_text='Stable upstream identifier for idempotent auto-creates (Stripe balance_transaction id, OrderItem id, PurchaseOrder id).', max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, help_text='Set for per-order expenses (Stripe fees, dropship cost).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='orders.order')),
                ('purchase_order', models.ForeignKey(blank=True, help_text='Set for inventory expenses tied to a wholesale PO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='procurement.purchaseorder')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['category', 'paid_at'], name='expenses_ex_categor_6f07d7_idx'), models.Index(fields=['paid_at'], name='expenses_ex_paid_at_db746e_idx'), models.Index(fields=['auto_created', 'category'], name='expenses_ex_auto_cr_cf8610_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_ref__gt', '')), fields=('category', 'external_ref'), name='uniq_auto_expense_per_ref')],
            },
        ),
    ]
